In [66]:
# Imports
import json 
import pandas as pd
from pandas import json_normalize
import numpy as np

In [69]:
# Create data object for JSON file 
data = [
    {
        "id": 1,
        "model": "1 Series",
        "colour": "white",
        "manufacturer": "BMW",
        "salesHistory": [
            {
                "year": 2011,
                "vehiclesSold": 2991
            },
            {
                "year": 2012,
                "vehiclesSold": 3228
            },
            {
                "year": 2013,
                "vehiclesSold": 7841
            },
            {
                "year": 2014,
                "vehiclesSold": 8458
            },
            {
                "year": 2015,
                "vehiclesSold": 7963
            },
            {
                "year": 2016,
                "vehiclesSold": 5220
            },
            {
                "year": 2017,
                "vehiclesSold": 7043
            },
            {
                "year": 2018,
                "vehiclesSold": 5369
            },
            {
                "year": 2019,
                "vehiclesSold": 3564
            },
            {
                "year": 2020,
                "vehiclesSold": 3646
            }
        ]
    },
    {
        "id": 2,
        "model": "2 Series",
        "colour": "black",
        "manufacturer": "BMW",
        "salesHistory": [
            {
                "year": 2011,
                "vehiclesSold": 8540
            },
            {
                "year": 2012,
                "vehiclesSold": 4274
            },
            {
                "year": 2013,
                "vehiclesSold": 6995
            },
            {
                "year": 2014,
                "vehiclesSold": 1618
            },
            {
                "year": 2015,
                "vehiclesSold": 3754
            },
            {
                "year": 2016,
                "vehiclesSold": 2048
            },
            {
                "year": 2017,
                "vehiclesSold": 2715
            },
            {
                "year": 2018,
                "vehiclesSold": 3626
            },
            {
                "year": 2019,
                "vehiclesSold": 9052
            },
            {
                "year": 2020,
                "vehiclesSold": 7605
            }
        ]
    },
    {
        "id": 3,
        "model": "3 Series",
        "colour": "black",
        "manufacturer": "BMW",
        "salesHistory": [
            {
                "year": 2011,
                "vehiclesSold": 6260
            },
            {
                "year": 2012,
                "vehiclesSold": 9637
            },
            {
                "year": 2013,
                "vehiclesSold": 5971
            },
            {
                "year": 2014,
                "vehiclesSold": 2467
            },
            {
                "year": 2015,
                "vehiclesSold": 7512
            },
            {
                "year": 2016,
                "vehiclesSold": 9483
            },
            {
                "year": 2017,
                "vehiclesSold": 7955
            },
            {
                "year": 2018,
                "vehiclesSold": 5098
            },
            {
                "year": 2019,
                "vehiclesSold": 9860
            },
            {
                "year": 2020,
                "vehiclesSold": 9051
            }
        ]
    },
    {
        "id": 4,
        "model": "A Class",
        "colour": "white",
        "manufacturer": "Mercedes",
        "salesHistory": [
            {
                "year": 2011,
                "vehiclesSold": 1508
            },
            {
                "year": 2012,
                "vehiclesSold": 8137
            },
            {
                "year": 2013,
                "vehiclesSold": 5572
            },
            {
                "year": 2014,
                "vehiclesSold": 6820
            },
            {
                "year": 2015,
                "vehiclesSold": 1387
            },
            {
                "year": 2016,
                "vehiclesSold": 8517
            },
            {
                "year": 2017,
                "vehiclesSold": 6608
            },
            {
                "year": 2018,
                "vehiclesSold": 6190
            },
            {
                "year": 2019,
                "vehiclesSold": 5956
            },
            {
                "year": 2020,
                "vehiclesSold": 5847
            }
        ]
    },
    {
        "id": 5,
        "model": "B Class",
        "colour": "grey",
        "manufacturer": "Mercedes",
        "salesHistory": [
            {
                "year": 2011,
                "vehiclesSold": 6176
            },
            {
                "year": 2012,
                "vehiclesSold": 8463
            },
            {
                "year": 2013,
                "vehiclesSold": 7981
            },
            {
                "year": 2014,
                "vehiclesSold": 9000
            },
            {
                "year": 2015,
                "vehiclesSold": 2978
            },
            {
                "year": 2016,
                "vehiclesSold": 8366
            },
            {
                "year": 2017,
                "vehiclesSold": 2109
            },
            {
                "year": 2018,
                "vehiclesSold": 3104
            },
            {
                "year": 2019,
                "vehiclesSold": 4170
            },
            {
                "year": 2020,
                "vehiclesSold": 4851
            }
        ]
    },
    {
        "id": 6,
        "model": "Golf",
        "colour": "white",
        "manufacturer": "VW",
        "salesHistory": [
            {
                "year": 2011,
                "vehiclesSold": 2767
            },
            {
                "year": 2012,
                "vehiclesSold": 4174
            },
            {
                "year": 2013,
                "vehiclesSold": 4398
            },
            {
                "year": 2014,
                "vehiclesSold": 5511
            },
            {
                "year": 2015,
                "vehiclesSold": 1584
            },
            {
                "year": 2016,
                "vehiclesSold": 9484
            },
            {
                "year": 2017,
                "vehiclesSold": 7953
            },
            {
                "year": 2018,
                "vehiclesSold": 9934
            },
            {
                "year": 2019,
                "vehiclesSold": 2575
            },
            {
                "year": 2020,
                "vehiclesSold": 9300
            }
        ]
    }
]

print(data)

[{'id': 1, 'model': '1 Series', 'colour': 'white', 'manufacturer': 'BMW', 'salesHistory': [{'year': 2011, 'vehiclesSold': 2991}, {'year': 2012, 'vehiclesSold': 3228}, {'year': 2013, 'vehiclesSold': 7841}, {'year': 2014, 'vehiclesSold': 8458}, {'year': 2015, 'vehiclesSold': 7963}, {'year': 2016, 'vehiclesSold': 5220}, {'year': 2017, 'vehiclesSold': 7043}, {'year': 2018, 'vehiclesSold': 5369}, {'year': 2019, 'vehiclesSold': 3564}, {'year': 2020, 'vehiclesSold': 3646}]}, {'id': 2, 'model': '2 Series', 'colour': 'black', 'manufacturer': 'BMW', 'salesHistory': [{'year': 2011, 'vehiclesSold': 8540}, {'year': 2012, 'vehiclesSold': 4274}, {'year': 2013, 'vehiclesSold': 6995}, {'year': 2014, 'vehiclesSold': 1618}, {'year': 2015, 'vehiclesSold': 3754}, {'year': 2016, 'vehiclesSold': 2048}, {'year': 2017, 'vehiclesSold': 2715}, {'year': 2018, 'vehiclesSold': 3626}, {'year': 2019, 'vehiclesSold': 9052}, {'year': 2020, 'vehiclesSold': 7605}]}, {'id': 3, 'model': '3 Series', 'colour': 'black', 'manufacturer': 'BMW', 'salesHistory': [{'year': 2011, 'vehiclesSold': 6260}, {'year': 2012, 'vehiclesSold': 9637}, {'year': 2013, 'vehiclesSold': 5971}, {'year': 2014, 'vehiclesSold': 2467}, {'year': 2015, 'vehiclesSold': 7512}, {'year': 2016, 'vehiclesSold': 9483}, {'year': 2017, 'vehiclesSold': 7955}, {'year': 2018, 'vehiclesSold': 5098}, {'year': 2019, 'vehiclesSold': 9860}, {'year': 2020, 'vehiclesSold': 9051}]}, {'id': 4, 'model': 'A Class', 'colour': 'white', 'manufacturer': 'Mercedes', 'salesHistory': [{'year': 2011, 'vehiclesSold': 1508}, {'year': 2012, 'vehiclesSold': 8137}, {'year': 2013, 'vehiclesSold': 5572}, {'year': 2014, 'vehiclesSold': 6820}, {'year': 2015, 'vehiclesSold': 1387}, {'year': 2016, 'vehiclesSold': 8517}, {'year': 2017, 'vehiclesSold': 6608}, {'year': 2018, 'vehiclesSold': 6190}, {'year': 2019, 'vehiclesSold': 5956}, {'year': 2020, 'vehiclesSold': 5847}]}, {'id': 5, 'model': 'B Class', 'colour': 'grey', 'manufacturer': 'Mercedes', 'salesHistory': [{'year': 2011, 'vehiclesSold': 6176}, {'year': 2012, 'vehiclesSold': 8463}, {'year': 2013, 'vehiclesSold': 7981}, {'year': 2014, 'vehiclesSold': 9000}, {'year': 2015, 'vehiclesSold': 2978}, {'year': 2016, 'vehiclesSold': 8366}, {'year': 2017, 'vehiclesSold': 2109}, {'year': 2018, 'vehiclesSold': 3104}, {'year': 2019, 'vehiclesSold': 4170}, {'year': 2020, 'vehiclesSold': 4851}]}, {'id': 6, 'model': 'Golf', 'colour': 'white', 'manufacturer': 'VW', 'salesHistory': [{'year': 2011, 'vehiclesSold': 2767}, {'year': 2012, 'vehiclesSold': 4174}, {'year': 2013, 'vehiclesSold': 4398}, {'year': 2014, 'vehiclesSold': 5511}, {'year': 2015, 'vehiclesSold': 1584}, {'year': 2016, 'vehiclesSold': 9484}, {'year': 2017, 'vehiclesSold': 7953}, {'year': 2018, 'vehiclesSold': 9934}, {'year': 2019, 'vehiclesSold': 2575}, {'year': 2020, 'vehiclesSold': 9300}]}]

In [68]:
#Flatten nested colums to flat table(result) for analysis
result = json_normalize(data, 'salesHistory', [ 'id','model','colour', 'manufacturer'])
result.head(10)

   year  vehiclesSold id     model colour manufacturer
0  2011          2991  1  1 Series  white          BMW
1  2012          3228  1  1 Series  white          BMW
2  2013          7841  1  1 Series  white          BMW
3  2014          8458  1  1 Series  white          BMW
4  2015          7963  1  1 Series  white          BMW
5  2016          5220  1  1 Series  white          BMW
6  2017          7043  1  1 Series  white          BMW
7  2018          5369  1  1 Series  white          BMW
8  2019          3564  1  1 Series  white          BMW
9  2020          3646  1  1 Series  white          BMW

In [70]:
# 1 •	How many of each model were sold throughout between 2011 -2020?
#o	Output – Should be a list of the vehicle models with the sum of the vehicles sold during that time period. Eg: 
#	Golf – 20000
#	Polo – 30000
#	1 Series - 10000 

#Group by model and total for each model sold
result.groupby(['model'])['vehiclesSold'].sum()

model
1 Series    55323
2 Series    50227
3 Series    73294
A Class     56542
B Class     57198
Golf        57680
Name: vehiclesSold, dtype: int64

In [71]:
# 2 •	Which manufacturer sold the most amount between 2011 -2020?
#o	Output – Should be a list of the vehicle models with the sum of the vehicles sold during that time period. Eg: 
#	VW – 20000
#	Mercedes – 30000
#	BMW - 10000  

# Group by manufacturer and most vehicles sold
result.groupby(['manufacturer']).agg({'vehiclesSold': [max]})

             vehiclesSold
                      max
manufacturer
BMW                  9860
Mercedes             9000
VW                   9934

In [76]:
# 3 •	The average number of vehicles sold across all manufacturers and models between 2011 -2020?
#o	Output – a single integer of the sum of all prices. Eg:
#	150000 

#Average of total vehicles sold
result['vehiclesSold'].sum() / 2

175132.0

In [42]:
# 4 •	What is the most common colour of vehicles sold between 2011 -2020?
#o	Output – a single string of the most common colour. Eg:
#	‘silver 

#Select most common colour in colour table
result['colour']. value_counts(). idxmax()

'white'